os: Visual Studio 2015

build:
  verbosity: detailed

install:
  - mkdir C:\projects\dependencies
  - cd C:\projects\dependencies

  # install cmake
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  # add clang to buildpath
  # - set PATH="C:\Program Files\LLVM\bin";%PATH%
  # - clang-cl -v
  - set PATH=C:\MinGW\bin;%PATH%

before_build:
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
  - cd C:\projects\two-coords
  - ps: (Get-Content .gitmodules).replace('git@github.com:', 'https://github.com/') | Set-Content .gitmodules
  - git submodule update --init --recursive
  - cd C:\projects\two-coords\thirdparty\glew\
  - C:\MinGW\msys\bin\bash -c "mingw32-make.exe -C auto"

build_script:
  - mkdir build
  - cd build
  - cmake .. -D
  - cmake --build . --target check
