install:
  - mkdir C:\projects\dependencies
  - cd C:\projects\dependencies

  # install cmake
  - set CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-win64-x64.zip"
  - appveyor DownloadFile %CMAKE_URL% -FileName cmake.zip
  - 7z x cmake.zip -oC:\projects\deps > nul
  - move C:\projects\deps\cmake-* C:\projects\deps\cmake # Move to a version-agnostic directory
  - set PATH=C:\projects\deps\cmake\bin;%PATH%
  - cmake --version

  # add clang to buildpath
  # - set PATH="C:\Program Files\LLVM\bin";%PATH%
  # - clang-cl -v

before_build:
  - cd C:\projects\two-coords
  - cscript //NoLogo sed.vbs s/(git@github.com:)/(https:\/\/github.com\/)/ < .gitmodules > .gitmodules
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target check
